-- Generated by tools/build-derived.js - do not edit by hand.

-- The twelve Maker_Class_Wise_* tables as one relation.
CREATE VIEW "_month_all_india" WITH (security_invoker = on) AS
    SELECT 1 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Jan"
    UNION ALL
    SELECT 2 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Feb"
    UNION ALL
    SELECT 3 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Mar"
    UNION ALL
    SELECT 4 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Apr"
    UNION ALL
    SELECT 5 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_May"
    UNION ALL
    SELECT 6 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Jun"
    UNION ALL
    SELECT 7 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Jul"
    UNION ALL
    SELECT 8 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Aug"
    UNION ALL
    SELECT 9 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Sep"
    UNION ALL
    SELECT 10 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Oct"
    UNION ALL
    SELECT 11 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Nov"
    UNION ALL
    SELECT 12 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Dec";

GRANT SELECT ON "_month_all_india" TO anon, authenticated;

-- The twelve Gujarat_Class_Wise_* tables as one relation.
CREATE VIEW "_month_gujarat" WITH (security_invoker = on) AS
    SELECT 1 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Jan"
    UNION ALL
    SELECT 2 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Feb"
    UNION ALL
    SELECT 3 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Mar"
    UNION ALL
    SELECT 4 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Apr"
    UNION ALL
    SELECT 5 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_May"
    UNION ALL
    SELECT 6 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Jun"
    UNION ALL
    SELECT 7 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Jul"
    UNION ALL
    SELECT 8 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Aug"
    UNION ALL
    SELECT 9 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Sep"
    UNION ALL
    SELECT 10 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Oct"
    UNION ALL
    SELECT 11 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Nov"
    UNION ALL
    SELECT 12 AS "month", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Total"
    FROM "Gujarat_Class_Wise_Dec";

GRANT SELECT ON "_month_gujarat" TO anon, authenticated;

-- The twelve Ahmedabad_Class_Wise_* tables as one relation.
CREATE VIEW "_month_ahmedabad" WITH (security_invoker = on) AS
    SELECT 1 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Jan"
    UNION ALL
    SELECT 2 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Feb"
    UNION ALL
    SELECT 3 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Mar"
    UNION ALL
    SELECT 4 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Apr"
    UNION ALL
    SELECT 5 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_May"
    UNION ALL
    SELECT 6 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Jun"
    UNION ALL
    SELECT 7 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Jul"
    UNION ALL
    SELECT 8 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Aug"
    UNION ALL
    SELECT 9 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Sep"
    UNION ALL
    SELECT 10 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Oct"
    UNION ALL
    SELECT 11 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Nov"
    UNION ALL
    SELECT 12 AS "month", "rto", "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Earth Moving Equipment", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle (Individual Use)", "Recovery Vehicle", "Tow Truck", "Tower Wagon", "Vehicle Fitted With Generator", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Quadricycle (Private)", "Breakdown Van", "Cash Van", "Omni Bus (Private Use)", "Total"
    FROM "Ahmedabad_Class_Wise_Dec";

GRANT SELECT ON "_month_ahmedabad" TO anon, authenticated;

-- GJ01 + GJ27 + GJ38 at year grain, for the Details card.
-- Summed per maker: the three RTOs share most of their makers,
-- so a plain UNION would list the same maker three times at a
-- third of its volume each.
CREATE VIEW "Ahmedabad_Class_Wise" WITH (security_invoker = on) AS
SELECT
    "year",
    "Maker",
    sum("Three Wheeler (Goods)")::integer AS "Three Wheeler (Goods)",
    sum("M-Cycle/Scooter")::integer AS "M-Cycle/Scooter",
    sum("Construction Equipment Vehicle")::integer AS "Construction Equipment Vehicle",
    sum("Crane Mounted Vehicle")::integer AS "Crane Mounted Vehicle",
    sum("Earth Moving Equipment")::integer AS "Earth Moving Equipment",
    sum("Bus")::integer AS "Bus",
    sum("Goods Carrier")::integer AS "Goods Carrier",
    sum("Mobile Clinic")::integer AS "Mobile Clinic",
    sum("Moped")::integer AS "Moped",
    sum("Three Wheeler (Passenger)")::integer AS "Three Wheeler (Passenger)",
    sum("e-Rickshaw with Cart (G)")::integer AS "e-Rickshaw with Cart (G)",
    sum("Motor Car")::integer AS "Motor Car",
    sum("Trailer (Agricultural)")::integer AS "Trailer (Agricultural)",
    sum("Motor Cab")::integer AS "Motor Cab",
    sum("Agricultural Tractor")::integer AS "Agricultural Tractor",
    sum("Tractor (Commercial)")::integer AS "Tractor (Commercial)",
    sum("e-Rickshaw(P)")::integer AS "e-Rickshaw(P)",
    sum("Ambulance")::integer AS "Ambulance",
    sum("Camper Van / Trailer")::integer AS "Camper Van / Trailer",
    sum("Camper Van / Trailer (Private Use)")::integer AS "Camper Van / Trailer (Private Use)",
    sum("Maxi Cab")::integer AS "Maxi Cab",
    sum("Adapted Vehicle")::integer AS "Adapted Vehicle",
    sum("M-Cycle/Scooter-With Side Car")::integer AS "M-Cycle/Scooter-With Side Car",
    sum("Motor Cycle/Scooter-Used For Hire")::integer AS "Motor Cycle/Scooter-Used For Hire",
    sum("Excavator (NT)")::integer AS "Excavator (NT)",
    sum("Fork Lift")::integer AS "Fork Lift",
    sum("Cash Van")::integer AS "Cash Van",
    sum("Fire Fighting Vehicle")::integer AS "Fire Fighting Vehicle",
    sum("Motorised Cycle (CC  25cc)")::integer AS "Motorised Cycle (CC  25cc)",
    sum("Trailer (Commercial)")::integer AS "Trailer (Commercial)",
    sum("Articulated Vehicle")::integer AS "Articulated Vehicle",
    sum("Recovery Vehicle")::integer AS "Recovery Vehicle",
    sum("Omni Bus (Private Use)")::integer AS "Omni Bus (Private Use)",
    sum("Fire Tenders")::integer AS "Fire Tenders",
    sum("Tower Wagon")::integer AS "Tower Wagon",
    sum("Vehicle Fitted With Generator")::integer AS "Vehicle Fitted With Generator",
    sum("Three Wheeler (Personal)")::integer AS "Three Wheeler (Personal)",
    sum("Private Service Vehicle (Individual Use)")::integer AS "Private Service Vehicle (Individual Use)",
    sum("Quadricycle (Private)")::integer AS "Quadricycle (Private)",
    sum("Dumper")::integer AS "Dumper",
    sum("Armoured/Specialised Vehicle")::integer AS "Armoured/Specialised Vehicle",
    sum("Mobile Workshop")::integer AS "Mobile Workshop",
    sum("Omni Bus")::integer AS "Omni Bus",
    sum("Vehicle Fitted With Rig")::integer AS "Vehicle Fitted With Rig",
    sum("Harvester")::integer AS "Harvester",
    sum("Animal Ambulance")::integer AS "Animal Ambulance",
    sum("Semi-Trailer (Commercial)")::integer AS "Semi-Trailer (Commercial)",
    sum("Educational Institution Bus")::integer AS "Educational Institution Bus",
    sum("Road Roller")::integer AS "Road Roller",
    sum("Total")::integer AS "Total"
FROM (
    SELECT "year", "Maker", "Three Wheeler (Goods)", "M-Cycle/Scooter", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Earth Moving Equipment", "Bus", "Goods Carrier", "Mobile Clinic", "Moped", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "Motor Car", "Trailer (Agricultural)", "Motor Cab", "Agricultural Tractor", "Tractor (Commercial)", "e-Rickshaw(P)", "Ambulance", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Maxi Cab", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Excavator (NT)", "Fork Lift", "Cash Van", "Fire Fighting Vehicle", "Motorised Cycle (CC  25cc)", "Trailer (Commercial)", "Articulated Vehicle", "Recovery Vehicle", "Omni Bus (Private Use)", "Fire Tenders", "Tower Wagon", "Vehicle Fitted With Generator", "Three Wheeler (Personal)", "Private Service Vehicle (Individual Use)", "Quadricycle (Private)", "Dumper", "Armoured/Specialised Vehicle", "Mobile Workshop", "Omni Bus", NULL::integer AS "Vehicle Fitted With Rig", NULL::integer AS "Harvester", NULL::integer AS "Animal Ambulance", NULL::integer AS "Semi-Trailer (Commercial)", NULL::integer AS "Educational Institution Bus", NULL::integer AS "Road Roller", "Total"
    FROM "Maker_Class_Wise_GJ01"
    UNION ALL
    SELECT "year", "Maker", "Three Wheeler (Goods)", "M-Cycle/Scooter", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Earth Moving Equipment", "Bus", "Goods Carrier", NULL::integer AS "Mobile Clinic", "Moped", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "Motor Car", "Trailer (Agricultural)", "Motor Cab", "Agricultural Tractor", "Tractor (Commercial)", "e-Rickshaw(P)", "Ambulance", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Maxi Cab", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Excavator (NT)", "Fork Lift", NULL::integer AS "Cash Van", "Fire Fighting Vehicle", "Motorised Cycle (CC  25cc)", "Trailer (Commercial)", "Articulated Vehicle", "Recovery Vehicle", NULL::integer AS "Omni Bus (Private Use)", NULL::integer AS "Fire Tenders", "Tower Wagon", "Vehicle Fitted With Generator", NULL::integer AS "Three Wheeler (Personal)", "Private Service Vehicle (Individual Use)", NULL::integer AS "Quadricycle (Private)", "Dumper", NULL::integer AS "Armoured/Specialised Vehicle", NULL::integer AS "Mobile Workshop", NULL::integer AS "Omni Bus", "Vehicle Fitted With Rig", "Harvester", "Animal Ambulance", "Semi-Trailer (Commercial)", NULL::integer AS "Educational Institution Bus", NULL::integer AS "Road Roller", "Total"
    FROM "Maker_Class_Wise_GJ27"
    UNION ALL
    SELECT "year", "Maker", "Three Wheeler (Goods)", "M-Cycle/Scooter", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Earth Moving Equipment", "Bus", "Goods Carrier", NULL::integer AS "Mobile Clinic", "Moped", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "Motor Car", "Trailer (Agricultural)", "Motor Cab", "Agricultural Tractor", "Tractor (Commercial)", "e-Rickshaw(P)", "Ambulance", NULL::integer AS "Camper Van / Trailer", NULL::integer AS "Camper Van / Trailer (Private Use)", "Maxi Cab", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", NULL::integer AS "Motor Cycle/Scooter-Used For Hire", NULL::integer AS "Excavator (NT)", "Fork Lift", NULL::integer AS "Cash Van", "Fire Fighting Vehicle", "Motorised Cycle (CC  25cc)", NULL::integer AS "Trailer (Commercial)", NULL::integer AS "Articulated Vehicle", "Recovery Vehicle", NULL::integer AS "Omni Bus (Private Use)", "Fire Tenders", NULL::integer AS "Tower Wagon", NULL::integer AS "Vehicle Fitted With Generator", NULL::integer AS "Three Wheeler (Personal)", "Private Service Vehicle (Individual Use)", NULL::integer AS "Quadricycle (Private)", "Dumper", NULL::integer AS "Armoured/Specialised Vehicle", NULL::integer AS "Mobile Workshop", "Omni Bus", NULL::integer AS "Vehicle Fitted With Rig", "Harvester", NULL::integer AS "Animal Ambulance", NULL::integer AS "Semi-Trailer (Commercial)", "Educational Institution Bus", "Road Roller", "Total"
    FROM "Maker_Class_Wise_GJ38"
) AS "parts"
GROUP BY "year", "Maker";

GRANT SELECT ON "Ahmedabad_Class_Wise" TO anon, authenticated;

-- Every scope at month grain. Ahmedabad is the RTO family
-- rolled up per maker; gj01/gj27/gj38 are the same family
-- filtered to one code.
CREATE VIEW "trend_by_maker" WITH (security_invoker = on) AS
    SELECT 'all_india'::text AS "scope", "year", "month", "Maker",
           "Three Wheeler (Goods)",
           "Three Wheeler (Passenger)",
           "e-Rickshaw with Cart (G)",
           "e-Rickshaw(P)",
           "Tractor-Trolley(Commercial)",
           "Trailer (Agricultural)",
           "Harvester",
           "Goods Carrier",
           "M-Cycle/Scooter",
           "Trailer (Commercial)",
           "Construction Equipment Vehicle",
           "Crane Mounted Vehicle",
           "Agricultural Tractor",
           "Construction Equipment Vehicle (Commercial)",
           "Earth Moving Equipment",
           "Excavator (Commercial)",
           "Excavator (NT)",
           "Fork Lift",
           "Road Roller",
           "Tractor (Commercial)",
           "Motorised Cycle (CC  25cc)",
           "Bus",
           "Semi-Trailer (Commercial)",
           "Motor Car",
           "Vehicle Fitted With Rig",
           "Moped",
           "Armoured/Specialised Vehicle",
           "Ambulance",
           "Animal Ambulance",
           "Articulated Vehicle",
           "Auxiliary Trailer",
           "Camper Van / Trailer",
           "Camper Van / Trailer (Private Use)",
           "Dumper",
           "Educational Institution Bus",
           "Fire Fighting Vehicle",
           "Fire Tenders",
           "Hearses",
           "Maxi Cab",
           "Mobile Canteen",
           "Mobile Clinic",
           "Mobile Workshop",
           "Omni Bus",
           "Private Service Vehicle",
           "Private Service Vehicle (Individual Use)",
           "Puller Tractor",
           "Recovery Vehicle",
           "School Bus",
           "Snorked Ladders",
           "Tow Truck",
           "Tower Wagon",
           "Tree Trimming Vehicle",
           "Vehicle Fitted With Compressor",
           "Vehicle Fitted With Generator",
           "X-Ray Van",
           "Adapted Vehicle",
           "M-Cycle/Scooter-With Side Car",
           "Motor Cycle/Scooter-Used For Hire",
           "Three Wheeler (Personal)",
           "Motor Cab",
           "Motor Cycle/Scooter-SideCar(T)",
           "Quadricycle (Commercial)",
           "Quadricycle (Private)",
           "Luxury Cab",
           "Breakdown Van",
           "Cash Van",
           "Library Van",
           "Omni Bus (Private Use)",
           "Vintage Motor Vehicle",
           "Trailer For Personal Use",
           "Motor Caravan",
           "Power Tiller",
           "Modular Hydraulic Trailer",
           "Bulldozer",
           "Motor Cycle/Scooter-With Trailer",
           "Total"
    FROM "_month_all_india"
    UNION ALL
    SELECT 'gujarat'::text AS "scope", "year", "month", "Maker",
           "Three Wheeler (Goods)",
           "Three Wheeler (Passenger)",
           "e-Rickshaw with Cart (G)",
           "e-Rickshaw(P)",
           "Tractor-Trolley(Commercial)",
           "Trailer (Agricultural)",
           "Harvester",
           "Goods Carrier",
           "M-Cycle/Scooter",
           "Trailer (Commercial)",
           "Construction Equipment Vehicle",
           "Crane Mounted Vehicle",
           "Agricultural Tractor",
           "Construction Equipment Vehicle (Commercial)",
           "Earth Moving Equipment",
           NULL::integer AS "Excavator (Commercial)",
           "Excavator (NT)",
           "Fork Lift",
           "Road Roller",
           "Tractor (Commercial)",
           "Motorised Cycle (CC  25cc)",
           "Bus",
           "Semi-Trailer (Commercial)",
           "Motor Car",
           "Vehicle Fitted With Rig",
           "Moped",
           "Armoured/Specialised Vehicle",
           "Ambulance",
           "Animal Ambulance",
           "Articulated Vehicle",
           "Auxiliary Trailer",
           "Camper Van / Trailer",
           "Camper Van / Trailer (Private Use)",
           "Dumper",
           "Educational Institution Bus",
           "Fire Fighting Vehicle",
           "Fire Tenders",
           "Hearses",
           "Maxi Cab",
           "Mobile Canteen",
           "Mobile Clinic",
           "Mobile Workshop",
           "Omni Bus",
           "Private Service Vehicle",
           "Private Service Vehicle (Individual Use)",
           NULL::integer AS "Puller Tractor",
           "Recovery Vehicle",
           NULL::integer AS "School Bus",
           "Snorked Ladders",
           "Tow Truck",
           "Tower Wagon",
           NULL::integer AS "Tree Trimming Vehicle",
           "Vehicle Fitted With Compressor",
           "Vehicle Fitted With Generator",
           "X-Ray Van",
           "Adapted Vehicle",
           "M-Cycle/Scooter-With Side Car",
           "Motor Cycle/Scooter-Used For Hire",
           "Three Wheeler (Personal)",
           "Motor Cab",
           "Motor Cycle/Scooter-SideCar(T)",
           NULL::integer AS "Quadricycle (Commercial)",
           "Quadricycle (Private)",
           NULL::integer AS "Luxury Cab",
           "Breakdown Van",
           "Cash Van",
           "Library Van",
           "Omni Bus (Private Use)",
           "Vintage Motor Vehicle",
           "Trailer For Personal Use",
           NULL::integer AS "Motor Caravan",
           NULL::integer AS "Power Tiller",
           NULL::integer AS "Modular Hydraulic Trailer",
           NULL::integer AS "Bulldozer",
           NULL::integer AS "Motor Cycle/Scooter-With Trailer",
           "Total"
    FROM "_month_gujarat"
    UNION ALL
    SELECT 'ahmedabad'::text AS "scope", "year", "month", "Maker",
           sum("Three Wheeler (Goods)")::integer AS "Three Wheeler (Goods)",
           sum("Three Wheeler (Passenger)")::integer AS "Three Wheeler (Passenger)",
           sum("e-Rickshaw with Cart (G)")::integer AS "e-Rickshaw with Cart (G)",
           sum("e-Rickshaw(P)")::integer AS "e-Rickshaw(P)",
           NULL::integer AS "Tractor-Trolley(Commercial)",
           sum("Trailer (Agricultural)")::integer AS "Trailer (Agricultural)",
           sum("Harvester")::integer AS "Harvester",
           sum("Goods Carrier")::integer AS "Goods Carrier",
           sum("M-Cycle/Scooter")::integer AS "M-Cycle/Scooter",
           sum("Trailer (Commercial)")::integer AS "Trailer (Commercial)",
           sum("Construction Equipment Vehicle")::integer AS "Construction Equipment Vehicle",
           sum("Crane Mounted Vehicle")::integer AS "Crane Mounted Vehicle",
           sum("Agricultural Tractor")::integer AS "Agricultural Tractor",
           NULL::integer AS "Construction Equipment Vehicle (Commercial)",
           sum("Earth Moving Equipment")::integer AS "Earth Moving Equipment",
           NULL::integer AS "Excavator (Commercial)",
           sum("Excavator (NT)")::integer AS "Excavator (NT)",
           sum("Fork Lift")::integer AS "Fork Lift",
           sum("Road Roller")::integer AS "Road Roller",
           sum("Tractor (Commercial)")::integer AS "Tractor (Commercial)",
           sum("Motorised Cycle (CC  25cc)")::integer AS "Motorised Cycle (CC  25cc)",
           sum("Bus")::integer AS "Bus",
           sum("Semi-Trailer (Commercial)")::integer AS "Semi-Trailer (Commercial)",
           sum("Motor Car")::integer AS "Motor Car",
           sum("Vehicle Fitted With Rig")::integer AS "Vehicle Fitted With Rig",
           sum("Moped")::integer AS "Moped",
           sum("Armoured/Specialised Vehicle")::integer AS "Armoured/Specialised Vehicle",
           sum("Ambulance")::integer AS "Ambulance",
           sum("Animal Ambulance")::integer AS "Animal Ambulance",
           sum("Articulated Vehicle")::integer AS "Articulated Vehicle",
           NULL::integer AS "Auxiliary Trailer",
           sum("Camper Van / Trailer")::integer AS "Camper Van / Trailer",
           sum("Camper Van / Trailer (Private Use)")::integer AS "Camper Van / Trailer (Private Use)",
           sum("Dumper")::integer AS "Dumper",
           sum("Educational Institution Bus")::integer AS "Educational Institution Bus",
           sum("Fire Fighting Vehicle")::integer AS "Fire Fighting Vehicle",
           sum("Fire Tenders")::integer AS "Fire Tenders",
           sum("Hearses")::integer AS "Hearses",
           sum("Maxi Cab")::integer AS "Maxi Cab",
           sum("Mobile Canteen")::integer AS "Mobile Canteen",
           sum("Mobile Clinic")::integer AS "Mobile Clinic",
           sum("Mobile Workshop")::integer AS "Mobile Workshop",
           sum("Omni Bus")::integer AS "Omni Bus",
           NULL::integer AS "Private Service Vehicle",
           sum("Private Service Vehicle (Individual Use)")::integer AS "Private Service Vehicle (Individual Use)",
           NULL::integer AS "Puller Tractor",
           sum("Recovery Vehicle")::integer AS "Recovery Vehicle",
           NULL::integer AS "School Bus",
           NULL::integer AS "Snorked Ladders",
           sum("Tow Truck")::integer AS "Tow Truck",
           sum("Tower Wagon")::integer AS "Tower Wagon",
           NULL::integer AS "Tree Trimming Vehicle",
           NULL::integer AS "Vehicle Fitted With Compressor",
           sum("Vehicle Fitted With Generator")::integer AS "Vehicle Fitted With Generator",
           NULL::integer AS "X-Ray Van",
           sum("Adapted Vehicle")::integer AS "Adapted Vehicle",
           sum("M-Cycle/Scooter-With Side Car")::integer AS "M-Cycle/Scooter-With Side Car",
           sum("Motor Cycle/Scooter-Used For Hire")::integer AS "Motor Cycle/Scooter-Used For Hire",
           sum("Three Wheeler (Personal)")::integer AS "Three Wheeler (Personal)",
           sum("Motor Cab")::integer AS "Motor Cab",
           NULL::integer AS "Motor Cycle/Scooter-SideCar(T)",
           NULL::integer AS "Quadricycle (Commercial)",
           sum("Quadricycle (Private)")::integer AS "Quadricycle (Private)",
           NULL::integer AS "Luxury Cab",
           sum("Breakdown Van")::integer AS "Breakdown Van",
           sum("Cash Van")::integer AS "Cash Van",
           NULL::integer AS "Library Van",
           sum("Omni Bus (Private Use)")::integer AS "Omni Bus (Private Use)",
           NULL::integer AS "Vintage Motor Vehicle",
           NULL::integer AS "Trailer For Personal Use",
           NULL::integer AS "Motor Caravan",
           NULL::integer AS "Power Tiller",
           NULL::integer AS "Modular Hydraulic Trailer",
           NULL::integer AS "Bulldozer",
           NULL::integer AS "Motor Cycle/Scooter-With Trailer",
           sum("Total")::integer AS "Total"
    FROM "_month_ahmedabad"
    GROUP BY "year", "month", "Maker"
    UNION ALL
    SELECT 'gj01'::text AS "scope", "year", "month", "Maker",
           "Three Wheeler (Goods)",
           "Three Wheeler (Passenger)",
           "e-Rickshaw with Cart (G)",
           "e-Rickshaw(P)",
           NULL::integer AS "Tractor-Trolley(Commercial)",
           "Trailer (Agricultural)",
           "Harvester",
           "Goods Carrier",
           "M-Cycle/Scooter",
           "Trailer (Commercial)",
           "Construction Equipment Vehicle",
           "Crane Mounted Vehicle",
           "Agricultural Tractor",
           NULL::integer AS "Construction Equipment Vehicle (Commercial)",
           "Earth Moving Equipment",
           NULL::integer AS "Excavator (Commercial)",
           "Excavator (NT)",
           "Fork Lift",
           "Road Roller",
           "Tractor (Commercial)",
           "Motorised Cycle (CC  25cc)",
           "Bus",
           "Semi-Trailer (Commercial)",
           "Motor Car",
           "Vehicle Fitted With Rig",
           "Moped",
           "Armoured/Specialised Vehicle",
           "Ambulance",
           "Animal Ambulance",
           "Articulated Vehicle",
           NULL::integer AS "Auxiliary Trailer",
           "Camper Van / Trailer",
           "Camper Van / Trailer (Private Use)",
           "Dumper",
           "Educational Institution Bus",
           "Fire Fighting Vehicle",
           "Fire Tenders",
           "Hearses",
           "Maxi Cab",
           "Mobile Canteen",
           "Mobile Clinic",
           "Mobile Workshop",
           "Omni Bus",
           NULL::integer AS "Private Service Vehicle",
           "Private Service Vehicle (Individual Use)",
           NULL::integer AS "Puller Tractor",
           "Recovery Vehicle",
           NULL::integer AS "School Bus",
           NULL::integer AS "Snorked Ladders",
           "Tow Truck",
           "Tower Wagon",
           NULL::integer AS "Tree Trimming Vehicle",
           NULL::integer AS "Vehicle Fitted With Compressor",
           "Vehicle Fitted With Generator",
           NULL::integer AS "X-Ray Van",
           "Adapted Vehicle",
           "M-Cycle/Scooter-With Side Car",
           "Motor Cycle/Scooter-Used For Hire",
           "Three Wheeler (Personal)",
           "Motor Cab",
           NULL::integer AS "Motor Cycle/Scooter-SideCar(T)",
           NULL::integer AS "Quadricycle (Commercial)",
           "Quadricycle (Private)",
           NULL::integer AS "Luxury Cab",
           "Breakdown Van",
           "Cash Van",
           NULL::integer AS "Library Van",
           "Omni Bus (Private Use)",
           NULL::integer AS "Vintage Motor Vehicle",
           NULL::integer AS "Trailer For Personal Use",
           NULL::integer AS "Motor Caravan",
           NULL::integer AS "Power Tiller",
           NULL::integer AS "Modular Hydraulic Trailer",
           NULL::integer AS "Bulldozer",
           NULL::integer AS "Motor Cycle/Scooter-With Trailer",
           "Total"
    FROM "_month_ahmedabad"
    WHERE "rto" = 'GJ01'
    UNION ALL
    SELECT 'gj27'::text AS "scope", "year", "month", "Maker",
           "Three Wheeler (Goods)",
           "Three Wheeler (Passenger)",
           "e-Rickshaw with Cart (G)",
           "e-Rickshaw(P)",
           NULL::integer AS "Tractor-Trolley(Commercial)",
           "Trailer (Agricultural)",
           "Harvester",
           "Goods Carrier",
           "M-Cycle/Scooter",
           "Trailer (Commercial)",
           "Construction Equipment Vehicle",
           "Crane Mounted Vehicle",
           "Agricultural Tractor",
           NULL::integer AS "Construction Equipment Vehicle (Commercial)",
           "Earth Moving Equipment",
           NULL::integer AS "Excavator (Commercial)",
           "Excavator (NT)",
           "Fork Lift",
           "Road Roller",
           "Tractor (Commercial)",
           "Motorised Cycle (CC  25cc)",
           "Bus",
           "Semi-Trailer (Commercial)",
           "Motor Car",
           "Vehicle Fitted With Rig",
           "Moped",
           "Armoured/Specialised Vehicle",
           "Ambulance",
           "Animal Ambulance",
           "Articulated Vehicle",
           NULL::integer AS "Auxiliary Trailer",
           "Camper Van / Trailer",
           "Camper Van / Trailer (Private Use)",
           "Dumper",
           "Educational Institution Bus",
           "Fire Fighting Vehicle",
           "Fire Tenders",
           "Hearses",
           "Maxi Cab",
           "Mobile Canteen",
           "Mobile Clinic",
           "Mobile Workshop",
           "Omni Bus",
           NULL::integer AS "Private Service Vehicle",
           "Private Service Vehicle (Individual Use)",
           NULL::integer AS "Puller Tractor",
           "Recovery Vehicle",
           NULL::integer AS "School Bus",
           NULL::integer AS "Snorked Ladders",
           "Tow Truck",
           "Tower Wagon",
           NULL::integer AS "Tree Trimming Vehicle",
           NULL::integer AS "Vehicle Fitted With Compressor",
           "Vehicle Fitted With Generator",
           NULL::integer AS "X-Ray Van",
           "Adapted Vehicle",
           "M-Cycle/Scooter-With Side Car",
           "Motor Cycle/Scooter-Used For Hire",
           "Three Wheeler (Personal)",
           "Motor Cab",
           NULL::integer AS "Motor Cycle/Scooter-SideCar(T)",
           NULL::integer AS "Quadricycle (Commercial)",
           "Quadricycle (Private)",
           NULL::integer AS "Luxury Cab",
           "Breakdown Van",
           "Cash Van",
           NULL::integer AS "Library Van",
           "Omni Bus (Private Use)",
           NULL::integer AS "Vintage Motor Vehicle",
           NULL::integer AS "Trailer For Personal Use",
           NULL::integer AS "Motor Caravan",
           NULL::integer AS "Power Tiller",
           NULL::integer AS "Modular Hydraulic Trailer",
           NULL::integer AS "Bulldozer",
           NULL::integer AS "Motor Cycle/Scooter-With Trailer",
           "Total"
    FROM "_month_ahmedabad"
    WHERE "rto" = 'GJ27'
    UNION ALL
    SELECT 'gj38'::text AS "scope", "year", "month", "Maker",
           "Three Wheeler (Goods)",
           "Three Wheeler (Passenger)",
           "e-Rickshaw with Cart (G)",
           "e-Rickshaw(P)",
           NULL::integer AS "Tractor-Trolley(Commercial)",
           "Trailer (Agricultural)",
           "Harvester",
           "Goods Carrier",
           "M-Cycle/Scooter",
           "Trailer (Commercial)",
           "Construction Equipment Vehicle",
           "Crane Mounted Vehicle",
           "Agricultural Tractor",
           NULL::integer AS "Construction Equipment Vehicle (Commercial)",
           "Earth Moving Equipment",
           NULL::integer AS "Excavator (Commercial)",
           "Excavator (NT)",
           "Fork Lift",
           "Road Roller",
           "Tractor (Commercial)",
           "Motorised Cycle (CC  25cc)",
           "Bus",
           "Semi-Trailer (Commercial)",
           "Motor Car",
           "Vehicle Fitted With Rig",
           "Moped",
           "Armoured/Specialised Vehicle",
           "Ambulance",
           "Animal Ambulance",
           "Articulated Vehicle",
           NULL::integer AS "Auxiliary Trailer",
           "Camper Van / Trailer",
           "Camper Van / Trailer (Private Use)",
           "Dumper",
           "Educational Institution Bus",
           "Fire Fighting Vehicle",
           "Fire Tenders",
           "Hearses",
           "Maxi Cab",
           "Mobile Canteen",
           "Mobile Clinic",
           "Mobile Workshop",
           "Omni Bus",
           NULL::integer AS "Private Service Vehicle",
           "Private Service Vehicle (Individual Use)",
           NULL::integer AS "Puller Tractor",
           "Recovery Vehicle",
           NULL::integer AS "School Bus",
           NULL::integer AS "Snorked Ladders",
           "Tow Truck",
           "Tower Wagon",
           NULL::integer AS "Tree Trimming Vehicle",
           NULL::integer AS "Vehicle Fitted With Compressor",
           "Vehicle Fitted With Generator",
           NULL::integer AS "X-Ray Van",
           "Adapted Vehicle",
           "M-Cycle/Scooter-With Side Car",
           "Motor Cycle/Scooter-Used For Hire",
           "Three Wheeler (Personal)",
           "Motor Cab",
           NULL::integer AS "Motor Cycle/Scooter-SideCar(T)",
           NULL::integer AS "Quadricycle (Commercial)",
           "Quadricycle (Private)",
           NULL::integer AS "Luxury Cab",
           "Breakdown Van",
           "Cash Van",
           NULL::integer AS "Library Van",
           "Omni Bus (Private Use)",
           NULL::integer AS "Vintage Motor Vehicle",
           NULL::integer AS "Trailer For Personal Use",
           NULL::integer AS "Motor Caravan",
           NULL::integer AS "Power Tiller",
           NULL::integer AS "Modular Hydraulic Trailer",
           NULL::integer AS "Bulldozer",
           NULL::integer AS "Motor Cycle/Scooter-With Trailer",
           "Total"
    FROM "_month_ahmedabad"
    WHERE "rto" = 'GJ38';

GRANT SELECT ON "trend_by_maker" TO anon, authenticated;

-- Answers IND on every render, and VOL too whenever no single
-- maker is chosen. 192 rows against the 54,019 below it.
CREATE VIEW "trend_totals" WITH (security_invoker = on) AS
SELECT
    "scope",
    "month",
    "year",
    sum("Three Wheeler (Goods)")::bigint AS "Three Wheeler (Goods)",
    sum("Three Wheeler (Passenger)")::bigint AS "Three Wheeler (Passenger)",
    sum("e-Rickshaw with Cart (G)")::bigint AS "e-Rickshaw with Cart (G)",
    sum("e-Rickshaw(P)")::bigint AS "e-Rickshaw(P)",
    sum("Tractor-Trolley(Commercial)")::bigint AS "Tractor-Trolley(Commercial)",
    sum("Trailer (Agricultural)")::bigint AS "Trailer (Agricultural)",
    sum("Harvester")::bigint AS "Harvester",
    sum("Goods Carrier")::bigint AS "Goods Carrier",
    sum("M-Cycle/Scooter")::bigint AS "M-Cycle/Scooter",
    sum("Trailer (Commercial)")::bigint AS "Trailer (Commercial)",
    sum("Construction Equipment Vehicle")::bigint AS "Construction Equipment Vehicle",
    sum("Crane Mounted Vehicle")::bigint AS "Crane Mounted Vehicle",
    sum("Agricultural Tractor")::bigint AS "Agricultural Tractor",
    sum("Construction Equipment Vehicle (Commercial)")::bigint AS "Construction Equipment Vehicle (Commercial)",
    sum("Earth Moving Equipment")::bigint AS "Earth Moving Equipment",
    sum("Excavator (Commercial)")::bigint AS "Excavator (Commercial)",
    sum("Excavator (NT)")::bigint AS "Excavator (NT)",
    sum("Fork Lift")::bigint AS "Fork Lift",
    sum("Road Roller")::bigint AS "Road Roller",
    sum("Tractor (Commercial)")::bigint AS "Tractor (Commercial)",
    sum("Motorised Cycle (CC  25cc)")::bigint AS "Motorised Cycle (CC  25cc)",
    sum("Bus")::bigint AS "Bus",
    sum("Semi-Trailer (Commercial)")::bigint AS "Semi-Trailer (Commercial)",
    sum("Motor Car")::bigint AS "Motor Car",
    sum("Vehicle Fitted With Rig")::bigint AS "Vehicle Fitted With Rig",
    sum("Moped")::bigint AS "Moped",
    sum("Armoured/Specialised Vehicle")::bigint AS "Armoured/Specialised Vehicle",
    sum("Ambulance")::bigint AS "Ambulance",
    sum("Animal Ambulance")::bigint AS "Animal Ambulance",
    sum("Articulated Vehicle")::bigint AS "Articulated Vehicle",
    sum("Auxiliary Trailer")::bigint AS "Auxiliary Trailer",
    sum("Camper Van / Trailer")::bigint AS "Camper Van / Trailer",
    sum("Camper Van / Trailer (Private Use)")::bigint AS "Camper Van / Trailer (Private Use)",
    sum("Dumper")::bigint AS "Dumper",
    sum("Educational Institution Bus")::bigint AS "Educational Institution Bus",
    sum("Fire Fighting Vehicle")::bigint AS "Fire Fighting Vehicle",
    sum("Fire Tenders")::bigint AS "Fire Tenders",
    sum("Hearses")::bigint AS "Hearses",
    sum("Maxi Cab")::bigint AS "Maxi Cab",
    sum("Mobile Canteen")::bigint AS "Mobile Canteen",
    sum("Mobile Clinic")::bigint AS "Mobile Clinic",
    sum("Mobile Workshop")::bigint AS "Mobile Workshop",
    sum("Omni Bus")::bigint AS "Omni Bus",
    sum("Private Service Vehicle")::bigint AS "Private Service Vehicle",
    sum("Private Service Vehicle (Individual Use)")::bigint AS "Private Service Vehicle (Individual Use)",
    sum("Puller Tractor")::bigint AS "Puller Tractor",
    sum("Recovery Vehicle")::bigint AS "Recovery Vehicle",
    sum("School Bus")::bigint AS "School Bus",
    sum("Snorked Ladders")::bigint AS "Snorked Ladders",
    sum("Tow Truck")::bigint AS "Tow Truck",
    sum("Tower Wagon")::bigint AS "Tower Wagon",
    sum("Tree Trimming Vehicle")::bigint AS "Tree Trimming Vehicle",
    sum("Vehicle Fitted With Compressor")::bigint AS "Vehicle Fitted With Compressor",
    sum("Vehicle Fitted With Generator")::bigint AS "Vehicle Fitted With Generator",
    sum("X-Ray Van")::bigint AS "X-Ray Van",
    sum("Adapted Vehicle")::bigint AS "Adapted Vehicle",
    sum("M-Cycle/Scooter-With Side Car")::bigint AS "M-Cycle/Scooter-With Side Car",
    sum("Motor Cycle/Scooter-Used For Hire")::bigint AS "Motor Cycle/Scooter-Used For Hire",
    sum("Three Wheeler (Personal)")::bigint AS "Three Wheeler (Personal)",
    sum("Motor Cab")::bigint AS "Motor Cab",
    sum("Motor Cycle/Scooter-SideCar(T)")::bigint AS "Motor Cycle/Scooter-SideCar(T)",
    sum("Quadricycle (Commercial)")::bigint AS "Quadricycle (Commercial)",
    sum("Quadricycle (Private)")::bigint AS "Quadricycle (Private)",
    sum("Luxury Cab")::bigint AS "Luxury Cab",
    sum("Breakdown Van")::bigint AS "Breakdown Van",
    sum("Cash Van")::bigint AS "Cash Van",
    sum("Library Van")::bigint AS "Library Van",
    sum("Omni Bus (Private Use)")::bigint AS "Omni Bus (Private Use)",
    sum("Vintage Motor Vehicle")::bigint AS "Vintage Motor Vehicle",
    sum("Trailer For Personal Use")::bigint AS "Trailer For Personal Use",
    sum("Motor Caravan")::bigint AS "Motor Caravan",
    sum("Power Tiller")::bigint AS "Power Tiller",
    sum("Modular Hydraulic Trailer")::bigint AS "Modular Hydraulic Trailer",
    sum("Bulldozer")::bigint AS "Bulldozer",
    sum("Motor Cycle/Scooter-With Trailer")::bigint AS "Motor Cycle/Scooter-With Trailer",
    sum("Total")::bigint AS "Total"
FROM "trend_by_maker"
GROUP BY "scope", "month", "year";

GRANT SELECT ON "trend_totals" TO anon, authenticated;

-- Per scope: All India has 2,552 names, GJ38 about 200, so a
-- scope-blind list would offer makers the grid cannot show.
CREATE VIEW "trend_makers" WITH (security_invoker = on) AS
SELECT DISTINCT "scope", "Maker" FROM "trend_by_maker";

GRANT SELECT ON "trend_makers" TO anon, authenticated;
