/*
 * Generates the views that sit on top of the 36 month tables.
 *
 * Writes  local/init/20-derived.sql
 *
 * Two layers, because a single view over 36 tables would be a
 * 72-branch UNION once the RTO scopes are expanded, and unreadable:
 *
 *   _month_all_india      the twelve All India tables as one
 *   _month_gujarat        relation each, with the month number the
 *   _month_ahmedabad      table name used to carry restored.
 *
 *   Ahmedabad_Class_Wise  year grain, for the Details card.
 *                         GJ01 + GJ27 + GJ38 summed PER MAKER.
 *
 *   trend_by_maker        all seven scopes as one relation, with a
 *                         "scope" column. Ahmedabad is a per-maker
 *                         rollup - the three RTOs share 289 of
 *                         their 590 maker entries, so concatenating
 *                         would triple-count.
 *   trend_totals          classes summed across makers.
 *   trend_makers          distinct makers per scope.
 *
 * Named trend_* rather than monthly_*: the live dashboard still
 * reads the monthly_* views with no scope filter, and reusing those
 * names would silently inflate its figures the moment these land.
 *
 * Usage:  node tools/build-derived.js   (after the two builders)
 */

const fs = require("fs");
const path = require("path");


const REPO_ROOT = path.resolve(__dirname, "..");

const CSV_DIR = path.join(REPO_ROOT, "local", "data");
const SQL_OUT = path.join(REPO_ROOT, "local", "init", "20-derived.sql");

const MONTHS = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
];

const AHMEDABAD_RTOS = ["GJ01", "GJ27", "GJ38"];

const FAMILIES = [
    { view: "_month_all_india", prefix: "Maker_Class_Wise_", hasRto: false },
    { view: "_month_gujarat", prefix: "Gujarat_Class_Wise_", hasRto: false },
    { view: "_month_ahmedabad", prefix: "Ahmedabad_Class_Wise_", hasRto: true }
];

/*
 * scope slug -> which family view it reads, and how. Slugs match
 * SCOPE_TABLES in script.js.
 */
const SCOPES = [
    { slug: "all_india", from: "_month_all_india", rto: null, group: false },
    { slug: "gujarat", from: "_month_gujarat", rto: null, group: false },
    { slug: "ahmedabad", from: "_month_ahmedabad", rto: null, group: true },
    { slug: "gj01", from: "_month_ahmedabad", rto: "GJ01", group: false },
    { slug: "gj27", from: "_month_ahmedabad", rto: "GJ27", group: false },
    { slug: "gj38", from: "_month_ahmedabad", rto: "GJ38", group: false }
];


function quote(name) {
    return `"${name.replace(/"/g, '""')}"`;
}


/* The header line of a generated CSV, minus the key columns. */
function classesOf(table, skip) {

    const header = fs
        .readFileSync(path.join(CSV_DIR, `${table}.csv`), "utf8")
        .split("\n")[0];

    const columns = [];
    let cell = "";
    let quoted = false;

    for (let at = 0; at < header.length; at += 1) {

        const character = header[at];

        if (quoted) {

            if (character === '"' && header[at + 1] === '"') {
                cell += '"';
                at += 1;
            } else if (character === '"') {
                quoted = false;
            } else {
                cell += character;
            }

        } else if (character === '"') {
            quoted = true;
        } else if (character === ",") {
            columns.push(cell);
            cell = "";
        } else {
            cell += character;
        }
    }

    columns.push(cell.replace(/\r$/, ""));

    return columns.filter(name => !skip.has(name));
}


function main() {

    const KEYS = new Set(["rto", "year", "Maker", "Total"]);

    const classesFor = new Map(
        FAMILIES.map(family => [
            family.view,
            classesOf(`${family.prefix}Jan`, KEYS)
        ])
    );

    /*
     * All India carries every class, so the others are subsets and
     * its order can serve as the union's order.
     */
    const ALL = classesFor.get("_month_all_india");

    for (const [view, columns] of classesFor) {
        for (const column of columns) {
            if (!ALL.includes(column)) {
                throw new Error(
                    `${view}: ${column} is absent from All India, so the ` +
                    "union cannot be built in All India's order"
                );
            }
        }
    }

    const sql = [
        "-- Generated by tools/build-derived.js - do not edit by hand.",
        ""
    ];

    /* ---- One relation per family ---- */

    for (const family of FAMILIES) {

        const columns = classesFor.get(family.view).map(quote).join(", ");

        const branches = MONTHS.map((month, index) =>
            `    SELECT ${index + 1} AS "month", ` +
            (family.hasRto ? '"rto", ' : "") +
            `"year", "Maker", ${columns}, "Total"\n` +
            `    FROM ${quote(`${family.prefix}${month}`)}`
        );

        sql.push(
            `-- The twelve ${family.prefix}* tables as one relation.`,
            `CREATE VIEW ${quote(family.view)} ` +
            "WITH (security_invoker = on) AS",
            branches.join("\n    UNION ALL\n") + ";",
            "",
            `GRANT SELECT ON ${quote(family.view)} TO anon, authenticated;`,
            ""
        );
    }

    /* ---- Ahmedabad at year grain, for the Details card ---- */

    const yearKeys = new Set(["year", "Maker", "Total"]);
    const yearClasses = [];

    for (const rto of AHMEDABAD_RTOS) {
        for (const name of classesOf(`Maker_Class_Wise_${rto}`, yearKeys)) {
            if (!yearClasses.includes(name)) {
                yearClasses.push(name);
            }
        }
    }

    const yearBranches = AHMEDABAD_RTOS.map(rto => {

        const has = new Set(classesOf(`Maker_Class_Wise_${rto}`, yearKeys));

        const columns = yearClasses.map(name =>
            has.has(name) ? quote(name) : `NULL::integer AS ${quote(name)}`
        );

        return (
            `    SELECT "year", "Maker", ${columns.join(", ")}, "Total"\n` +
            `    FROM ${quote(`Maker_Class_Wise_${rto}`)}`
        );
    });

    sql.push(
        "-- GJ01 + GJ27 + GJ38 at year grain, for the Details card.",
        "-- Summed per maker: the three RTOs share most of their makers,",
        "-- so a plain UNION would list the same maker three times at a",
        "-- third of its volume each.",
        'CREATE VIEW "Ahmedabad_Class_Wise" WITH (security_invoker = on) AS',
        "SELECT",
        '    "year",',
        '    "Maker",',
        ...yearClasses.map(
            name => `    sum(${quote(name)})::integer AS ${quote(name)},`
        ),
        '    sum("Total")::integer AS "Total"',
        "FROM (",
        yearBranches.join("\n    UNION ALL\n"),
        ') AS "parts"',
        'GROUP BY "year", "Maker";',
        "",
        'GRANT SELECT ON "Ahmedabad_Class_Wise" TO anon, authenticated;',
        ""
    );

    /* ---- trend_by_maker: every scope as one relation ---- */

    const branches = SCOPES.map(scope => {

        const own = new Set(classesFor.get(scope.from));

        const head =
            `    SELECT '${scope.slug}'::text AS "scope", ` +
            '"year", "month", "Maker",\n           ';

        if (scope.group) {

            const columns = ALL.map(name =>
                own.has(name)
                    ? `sum(${quote(name)})::integer AS ${quote(name)}`
                    : `NULL::integer AS ${quote(name)}`
            );

            return (
                head + columns.join(",\n           ") + ",\n" +
                '           sum("Total")::integer AS "Total"\n' +
                `    FROM ${quote(scope.from)}\n` +
                '    GROUP BY "year", "month", "Maker"'
            );
        }

        const columns = ALL.map(name =>
            own.has(name) ? quote(name) : `NULL::integer AS ${quote(name)}`
        );

        return (
            head + columns.join(",\n           ") + ",\n" +
            '           "Total"\n' +
            `    FROM ${quote(scope.from)}` +
            (scope.rto ? `\n    WHERE "rto" = '${scope.rto}'` : "")
        );
    });

    sql.push(
        "-- Every scope at month grain. Ahmedabad is the RTO family",
        "-- rolled up per maker; gj01/gj27/gj38 are the same family",
        "-- filtered to one code.",
        'CREATE VIEW "trend_by_maker" WITH (security_invoker = on) AS',
        branches.join("\n    UNION ALL\n") + ";",
        "",
        'GRANT SELECT ON "trend_by_maker" TO anon, authenticated;',
        ""
    );

    /* ---- trend_totals ---- */

    sql.push(
        "-- Answers IND on every render, and VOL too whenever no single",
        "-- maker is chosen. 192 rows against the 54,019 below it.",
        'CREATE VIEW "trend_totals" WITH (security_invoker = on) AS',
        "SELECT",
        '    "scope",',
        '    "month",',
        '    "year",',
        ...ALL.map(name => `    sum(${quote(name)})::bigint AS ${quote(name)},`),
        '    sum("Total")::bigint AS "Total"',
        'FROM "trend_by_maker"',
        'GROUP BY "scope", "month", "year";',
        "",
        'GRANT SELECT ON "trend_totals" TO anon, authenticated;',
        ""
    );

    /* ---- trend_makers ---- */

    sql.push(
        "-- Per scope: All India has 2,552 names, GJ38 about 200, so a",
        "-- scope-blind list would offer makers the grid cannot show.",
        'CREATE VIEW "trend_makers" WITH (security_invoker = on) AS',
        'SELECT DISTINCT "scope", "Maker" FROM "trend_by_maker";',
        "",
        'GRANT SELECT ON "trend_makers" TO anon, authenticated;',
        ""
    );

    fs.writeFileSync(SQL_OUT, sql.join("\n"), "utf8");

    console.log(`SQL -> ${SQL_OUT}`);
    console.log(`family views:  ${FAMILIES.map(f => f.view).join(", ")}`);
    console.log(`union classes: ${ALL.length}`);
    console.log(`Ahmedabad year-grain classes: ${yearClasses.length}`);
    console.log(`scopes: ${SCOPES.map(s => s.slug).join(", ")}`);
}


main();
