-- Generated by tools/create-monthly-views.js - do not edit by hand.
--
-- Aggregates for the monthly trend. Without these the browser
-- pages all 37,074 maker-rows to fill a 4 x 12 grid.

DROP VIEW IF EXISTS "monthly_makers";
DROP VIEW IF EXISTS "monthly_totals";
DROP VIEW IF EXISTS "monthly_by_maker";

-- The twelve month tables as one relation.
CREATE VIEW "monthly_by_maker" WITH (security_invoker = on) AS
    SELECT 1 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Jan"
    UNION ALL
    SELECT 2 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Feb"
    UNION ALL
    SELECT 3 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Mar"
    UNION ALL
    SELECT 4 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Apr"
    UNION ALL
    SELECT 5 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_May"
    UNION ALL
    SELECT 6 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Jun"
    UNION ALL
    SELECT 7 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Jul"
    UNION ALL
    SELECT 8 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Aug"
    UNION ALL
    SELECT 9 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Sep"
    UNION ALL
    SELECT 10 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Oct"
    UNION ALL
    SELECT 11 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Nov"
    UNION ALL
    SELECT 12 AS month, "year", "Maker", "Three Wheeler (Goods)", "Three Wheeler (Passenger)", "e-Rickshaw with Cart (G)", "e-Rickshaw(P)", "Tractor-Trolley(Commercial)", "Trailer (Agricultural)", "Harvester", "Goods Carrier", "M-Cycle/Scooter", "Trailer (Commercial)", "Construction Equipment Vehicle", "Crane Mounted Vehicle", "Agricultural Tractor", "Construction Equipment Vehicle (Commercial)", "Earth Moving Equipment", "Excavator (Commercial)", "Excavator (NT)", "Fork Lift", "Road Roller", "Tractor (Commercial)", "Motorised Cycle (CC  25cc)", "Bus", "Semi-Trailer (Commercial)", "Motor Car", "Vehicle Fitted With Rig", "Moped", "Armoured/Specialised Vehicle", "Ambulance", "Animal Ambulance", "Articulated Vehicle", "Auxiliary Trailer", "Camper Van / Trailer", "Camper Van / Trailer (Private Use)", "Dumper", "Educational Institution Bus", "Fire Fighting Vehicle", "Fire Tenders", "Hearses", "Maxi Cab", "Mobile Canteen", "Mobile Clinic", "Mobile Workshop", "Omni Bus", "Private Service Vehicle", "Private Service Vehicle (Individual Use)", "Puller Tractor", "Recovery Vehicle", "School Bus", "Snorked Ladders", "Tow Truck", "Tower Wagon", "Tree Trimming Vehicle", "Vehicle Fitted With Compressor", "Vehicle Fitted With Generator", "X-Ray Van", "Adapted Vehicle", "M-Cycle/Scooter-With Side Car", "Motor Cycle/Scooter-Used For Hire", "Three Wheeler (Personal)", "Motor Cab", "Motor Cycle/Scooter-SideCar(T)", "Quadricycle (Commercial)", "Quadricycle (Private)", "Luxury Cab", "Breakdown Van", "Cash Van", "Library Van", "Omni Bus (Private Use)", "Vintage Motor Vehicle", "Trailer For Personal Use", "Motor Caravan", "Power Tiller", "Modular Hydraulic Trailer", "Bulldozer", "Motor Cycle/Scooter-With Trailer", "Total"
    FROM "Maker_Class_Wise_Dec";

-- Every class summed across makers, per month and year.
CREATE VIEW "monthly_totals" WITH (security_invoker = on) AS
SELECT
    month,
    "year",
    sum("Three Wheeler (Goods)")::bigint AS "Three Wheeler (Goods)",
    sum("Three Wheeler (Passenger)")::bigint AS "Three Wheeler (Passenger)",
    sum("e-Rickshaw with Cart (G)")::bigint AS "e-Rickshaw with Cart (G)",
    sum("e-Rickshaw(P)")::bigint AS "e-Rickshaw(P)",
    sum("Tractor-Trolley(Commercial)")::bigint AS "Tractor-Trolley(Commercial)",
    sum("Trailer (Agricultural)")::bigint AS "Trailer (Agricultural)",
    sum("Harvester")::bigint AS "Harvester",
    sum("Goods Carrier")::bigint AS "Goods Carrier",
    sum("M-Cycle/Scooter")::bigint AS "M-Cycle/Scooter",
    sum("Trailer (Commercial)")::bigint AS "Trailer (Commercial)",
    sum("Construction Equipment Vehicle")::bigint AS "Construction Equipment Vehicle",
    sum("Crane Mounted Vehicle")::bigint AS "Crane Mounted Vehicle",
    sum("Agricultural Tractor")::bigint AS "Agricultural Tractor",
    sum("Construction Equipment Vehicle (Commercial)")::bigint AS "Construction Equipment Vehicle (Commercial)",
    sum("Earth Moving Equipment")::bigint AS "Earth Moving Equipment",
    sum("Excavator (Commercial)")::bigint AS "Excavator (Commercial)",
    sum("Excavator (NT)")::bigint AS "Excavator (NT)",
    sum("Fork Lift")::bigint AS "Fork Lift",
    sum("Road Roller")::bigint AS "Road Roller",
    sum("Tractor (Commercial)")::bigint AS "Tractor (Commercial)",
    sum("Motorised Cycle (CC  25cc)")::bigint AS "Motorised Cycle (CC  25cc)",
    sum("Bus")::bigint AS "Bus",
    sum("Semi-Trailer (Commercial)")::bigint AS "Semi-Trailer (Commercial)",
    sum("Motor Car")::bigint AS "Motor Car",
    sum("Vehicle Fitted With Rig")::bigint AS "Vehicle Fitted With Rig",
    sum("Moped")::bigint AS "Moped",
    sum("Armoured/Specialised Vehicle")::bigint AS "Armoured/Specialised Vehicle",
    sum("Ambulance")::bigint AS "Ambulance",
    sum("Animal Ambulance")::bigint AS "Animal Ambulance",
    sum("Articulated Vehicle")::bigint AS "Articulated Vehicle",
    sum("Auxiliary Trailer")::bigint AS "Auxiliary Trailer",
    sum("Camper Van / Trailer")::bigint AS "Camper Van / Trailer",
    sum("Camper Van / Trailer (Private Use)")::bigint AS "Camper Van / Trailer (Private Use)",
    sum("Dumper")::bigint AS "Dumper",
    sum("Educational Institution Bus")::bigint AS "Educational Institution Bus",
    sum("Fire Fighting Vehicle")::bigint AS "Fire Fighting Vehicle",
    sum("Fire Tenders")::bigint AS "Fire Tenders",
    sum("Hearses")::bigint AS "Hearses",
    sum("Maxi Cab")::bigint AS "Maxi Cab",
    sum("Mobile Canteen")::bigint AS "Mobile Canteen",
    sum("Mobile Clinic")::bigint AS "Mobile Clinic",
    sum("Mobile Workshop")::bigint AS "Mobile Workshop",
    sum("Omni Bus")::bigint AS "Omni Bus",
    sum("Private Service Vehicle")::bigint AS "Private Service Vehicle",
    sum("Private Service Vehicle (Individual Use)")::bigint AS "Private Service Vehicle (Individual Use)",
    sum("Puller Tractor")::bigint AS "Puller Tractor",
    sum("Recovery Vehicle")::bigint AS "Recovery Vehicle",
    sum("School Bus")::bigint AS "School Bus",
    sum("Snorked Ladders")::bigint AS "Snorked Ladders",
    sum("Tow Truck")::bigint AS "Tow Truck",
    sum("Tower Wagon")::bigint AS "Tower Wagon",
    sum("Tree Trimming Vehicle")::bigint AS "Tree Trimming Vehicle",
    sum("Vehicle Fitted With Compressor")::bigint AS "Vehicle Fitted With Compressor",
    sum("Vehicle Fitted With Generator")::bigint AS "Vehicle Fitted With Generator",
    sum("X-Ray Van")::bigint AS "X-Ray Van",
    sum("Adapted Vehicle")::bigint AS "Adapted Vehicle",
    sum("M-Cycle/Scooter-With Side Car")::bigint AS "M-Cycle/Scooter-With Side Car",
    sum("Motor Cycle/Scooter-Used For Hire")::bigint AS "Motor Cycle/Scooter-Used For Hire",
    sum("Three Wheeler (Personal)")::bigint AS "Three Wheeler (Personal)",
    sum("Motor Cab")::bigint AS "Motor Cab",
    sum("Motor Cycle/Scooter-SideCar(T)")::bigint AS "Motor Cycle/Scooter-SideCar(T)",
    sum("Quadricycle (Commercial)")::bigint AS "Quadricycle (Commercial)",
    sum("Quadricycle (Private)")::bigint AS "Quadricycle (Private)",
    sum("Luxury Cab")::bigint AS "Luxury Cab",
    sum("Breakdown Van")::bigint AS "Breakdown Van",
    sum("Cash Van")::bigint AS "Cash Van",
    sum("Library Van")::bigint AS "Library Van",
    sum("Omni Bus (Private Use)")::bigint AS "Omni Bus (Private Use)",
    sum("Vintage Motor Vehicle")::bigint AS "Vintage Motor Vehicle",
    sum("Trailer For Personal Use")::bigint AS "Trailer For Personal Use",
    sum("Motor Caravan")::bigint AS "Motor Caravan",
    sum("Power Tiller")::bigint AS "Power Tiller",
    sum("Modular Hydraulic Trailer")::bigint AS "Modular Hydraulic Trailer",
    sum("Bulldozer")::bigint AS "Bulldozer",
    sum("Motor Cycle/Scooter-With Trailer")::bigint AS "Motor Cycle/Scooter-With Trailer",
    sum("Total")::bigint AS "Total"
FROM "monthly_by_maker"
GROUP BY month, "year";

-- Distinct makers, for the trend's own Maker select.
CREATE VIEW "monthly_makers" WITH (security_invoker = on) AS
SELECT DISTINCT "Maker" FROM "monthly_by_maker";

GRANT SELECT ON "monthly_by_maker" TO anon, authenticated;
GRANT SELECT ON "monthly_totals"   TO anon, authenticated;
GRANT SELECT ON "monthly_makers"   TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
