-- Generated by tools/build-month-tables.js - do not edit by hand.
--
-- Twelve month tables for Maker x Vehicle Class. The year is a
-- column, not part of the table name, so a new year is a new set
-- of rows rather than a new set of tables.
--
-- 78 columns: year, Maker, 75 vehicle classes, Total.
-- Class names are the raw Vahan headers, matching the existing
-- MAKER_WISE_* tables, so the CLASS_GROUPS regexes in script.js
-- keep classifying them correctly.
--
-- The SELECT-only policy mirrors the existing tables: the
-- publishable key in script.js stays read-only. The GRANT is
-- explicit rather than left to the project's default privileges,
-- which have been hand-edited before and cannot be assumed.

GRANT USAGE ON SCHEMA public TO anon, authenticated;

CREATE TABLE "Maker_Class_Wise_Jan" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Jan" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Jan" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Jan" ON "Maker_Class_Wise_Jan";

CREATE POLICY "anon read Jan" ON "Maker_Class_Wise_Jan"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Feb" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Feb" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Feb" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Feb" ON "Maker_Class_Wise_Feb";

CREATE POLICY "anon read Feb" ON "Maker_Class_Wise_Feb"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Mar" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Mar" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Mar" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Mar" ON "Maker_Class_Wise_Mar";

CREATE POLICY "anon read Mar" ON "Maker_Class_Wise_Mar"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Apr" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Apr" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Apr" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Apr" ON "Maker_Class_Wise_Apr";

CREATE POLICY "anon read Apr" ON "Maker_Class_Wise_Apr"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_May" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_May" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_May" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read May" ON "Maker_Class_Wise_May";

CREATE POLICY "anon read May" ON "Maker_Class_Wise_May"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Jun" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Jun" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Jun" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Jun" ON "Maker_Class_Wise_Jun";

CREATE POLICY "anon read Jun" ON "Maker_Class_Wise_Jun"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Jul" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Jul" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Jul" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Jul" ON "Maker_Class_Wise_Jul";

CREATE POLICY "anon read Jul" ON "Maker_Class_Wise_Jul"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Aug" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Aug" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Aug" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Aug" ON "Maker_Class_Wise_Aug";

CREATE POLICY "anon read Aug" ON "Maker_Class_Wise_Aug"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Sep" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Sep" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Sep" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Sep" ON "Maker_Class_Wise_Sep";

CREATE POLICY "anon read Sep" ON "Maker_Class_Wise_Sep"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Oct" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Oct" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Oct" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Oct" ON "Maker_Class_Wise_Oct";

CREATE POLICY "anon read Oct" ON "Maker_Class_Wise_Oct"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Nov" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Nov" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Nov" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Nov" ON "Maker_Class_Wise_Nov";

CREATE POLICY "anon read Nov" ON "Maker_Class_Wise_Nov"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maker_Class_Wise_Dec" (
    "year"                                        smallint NOT NULL,
    "Maker"                                       text     NOT NULL,
    "Three Wheeler (Goods)"                       integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Passenger)"                   integer  NOT NULL DEFAULT 0,
    "e-Rickshaw with Cart (G)"                    integer  NOT NULL DEFAULT 0,
    "e-Rickshaw(P)"                               integer  NOT NULL DEFAULT 0,
    "Tractor-Trolley(Commercial)"                 integer  NOT NULL DEFAULT 0,
    "Trailer (Agricultural)"                      integer  NOT NULL DEFAULT 0,
    "Harvester"                                   integer  NOT NULL DEFAULT 0,
    "Goods Carrier"                               integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter"                             integer  NOT NULL DEFAULT 0,
    "Trailer (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle"              integer  NOT NULL DEFAULT 0,
    "Crane Mounted Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Agricultural Tractor"                        integer  NOT NULL DEFAULT 0,
    "Construction Equipment Vehicle (Commercial)" integer  NOT NULL DEFAULT 0,
    "Earth Moving Equipment"                      integer  NOT NULL DEFAULT 0,
    "Excavator (Commercial)"                      integer  NOT NULL DEFAULT 0,
    "Excavator (NT)"                              integer  NOT NULL DEFAULT 0,
    "Fork Lift"                                   integer  NOT NULL DEFAULT 0,
    "Road Roller"                                 integer  NOT NULL DEFAULT 0,
    "Tractor (Commercial)"                        integer  NOT NULL DEFAULT 0,
    "Motorised Cycle (CC  25cc)"                  integer  NOT NULL DEFAULT 0,
    "Bus"                                         integer  NOT NULL DEFAULT 0,
    "Semi-Trailer (Commercial)"                   integer  NOT NULL DEFAULT 0,
    "Motor Car"                                   integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Rig"                     integer  NOT NULL DEFAULT 0,
    "Moped"                                       integer  NOT NULL DEFAULT 0,
    "Armoured/Specialised Vehicle"                integer  NOT NULL DEFAULT 0,
    "Ambulance"                                   integer  NOT NULL DEFAULT 0,
    "Animal Ambulance"                            integer  NOT NULL DEFAULT 0,
    "Articulated Vehicle"                         integer  NOT NULL DEFAULT 0,
    "Auxiliary Trailer"                           integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer"                        integer  NOT NULL DEFAULT 0,
    "Camper Van / Trailer (Private Use)"          integer  NOT NULL DEFAULT 0,
    "Dumper"                                      integer  NOT NULL DEFAULT 0,
    "Educational Institution Bus"                 integer  NOT NULL DEFAULT 0,
    "Fire Fighting Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Fire Tenders"                                integer  NOT NULL DEFAULT 0,
    "Hearses"                                     integer  NOT NULL DEFAULT 0,
    "Maxi Cab"                                    integer  NOT NULL DEFAULT 0,
    "Mobile Canteen"                              integer  NOT NULL DEFAULT 0,
    "Mobile Clinic"                               integer  NOT NULL DEFAULT 0,
    "Mobile Workshop"                             integer  NOT NULL DEFAULT 0,
    "Omni Bus"                                    integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle"                     integer  NOT NULL DEFAULT 0,
    "Private Service Vehicle (Individual Use)"    integer  NOT NULL DEFAULT 0,
    "Puller Tractor"                              integer  NOT NULL DEFAULT 0,
    "Recovery Vehicle"                            integer  NOT NULL DEFAULT 0,
    "School Bus"                                  integer  NOT NULL DEFAULT 0,
    "Snorked Ladders"                             integer  NOT NULL DEFAULT 0,
    "Tow Truck"                                   integer  NOT NULL DEFAULT 0,
    "Tower Wagon"                                 integer  NOT NULL DEFAULT 0,
    "Tree Trimming Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Compressor"              integer  NOT NULL DEFAULT 0,
    "Vehicle Fitted With Generator"               integer  NOT NULL DEFAULT 0,
    "X-Ray Van"                                   integer  NOT NULL DEFAULT 0,
    "Adapted Vehicle"                             integer  NOT NULL DEFAULT 0,
    "M-Cycle/Scooter-With Side Car"               integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-Used For Hire"           integer  NOT NULL DEFAULT 0,
    "Three Wheeler (Personal)"                    integer  NOT NULL DEFAULT 0,
    "Motor Cab"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-SideCar(T)"              integer  NOT NULL DEFAULT 0,
    "Quadricycle (Commercial)"                    integer  NOT NULL DEFAULT 0,
    "Quadricycle (Private)"                       integer  NOT NULL DEFAULT 0,
    "Luxury Cab"                                  integer  NOT NULL DEFAULT 0,
    "Breakdown Van"                               integer  NOT NULL DEFAULT 0,
    "Cash Van"                                    integer  NOT NULL DEFAULT 0,
    "Library Van"                                 integer  NOT NULL DEFAULT 0,
    "Omni Bus (Private Use)"                      integer  NOT NULL DEFAULT 0,
    "Vintage Motor Vehicle"                       integer  NOT NULL DEFAULT 0,
    "Trailer For Personal Use"                    integer  NOT NULL DEFAULT 0,
    "Motor Caravan"                               integer  NOT NULL DEFAULT 0,
    "Power Tiller"                                integer  NOT NULL DEFAULT 0,
    "Modular Hydraulic Trailer"                   integer  NOT NULL DEFAULT 0,
    "Bulldozer"                                   integer  NOT NULL DEFAULT 0,
    "Motor Cycle/Scooter-With Trailer"            integer  NOT NULL DEFAULT 0,
    "Total"                                       integer  NOT NULL DEFAULT 0,
    PRIMARY KEY ("year", "Maker"),
    CHECK ("year" BETWEEN 2000 AND 2100)
);

ALTER TABLE "Maker_Class_Wise_Dec" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maker_Class_Wise_Dec" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Dec" ON "Maker_Class_Wise_Dec";

CREATE POLICY "anon read Dec" ON "Maker_Class_Wise_Dec"
    FOR SELECT TO anon, authenticated USING (true);

/*
 * PostgREST caches the schema, so a brand new table can 404 over
 * REST for a few seconds. This forces the reload.
 */
NOTIFY pgrst, 'reload schema';

-- ------------------------------------------------------------
-- Loading
-- ------------------------------------------------------------
--
-- Import RTO/month-tables/<Mon>.csv into the matching table via
-- Table Editor -> Import data from CSV.
--
-- Vahan restates past months as late registrations arrive. Each
-- CSV holds every year for its month, so a reload is a truncate
-- and a re-import, not an append:
--
--     TRUNCATE TABLE "Maker_Class_Wise_Jan";
--
-- Re-running tools/build-month-tables.js first picks up the new
-- workbook. Replacing the whole table is what makes a maker that
-- vanished from the new export actually vanish.
--
-- Do NOT delete a single year and then re-import the merged CSV -
-- the rows for the other years are still present and the import
-- fails on the (year, Maker) primary key. Deleting one year is
-- only useful if you are importing a single-year file:
--
--     DELETE FROM "Maker_Class_Wise_Jan" WHERE "year" = 2026;
--
-- ------------------------------------------------------------
-- Verification
-- ------------------------------------------------------------
--
-- Row count and unit total per year:
--
--     SELECT "year", count(*), sum("Total")
--     FROM "Maker_Class_Wise_Jan"
--     GROUP BY "year" ORDER BY "year";
--
-- Total must equal the sum of the 75 class columns. Expect zero rows:
--
--     SELECT "year", "Maker" FROM "Maker_Class_Wise_Jan"
--     WHERE "Total" <> (
--         "Three Wheeler (Goods)" +
--         "Three Wheeler (Passenger)" +
--         "e-Rickshaw with Cart (G)" +
--         "e-Rickshaw(P)" +
--         "Tractor-Trolley(Commercial)" +
--         "Trailer (Agricultural)" +
--         "Harvester" +
--         "Goods Carrier" +
--         "M-Cycle/Scooter" +
--         "Trailer (Commercial)" +
--         "Construction Equipment Vehicle" +
--         "Crane Mounted Vehicle" +
--         "Agricultural Tractor" +
--         "Construction Equipment Vehicle (Commercial)" +
--         "Earth Moving Equipment" +
--         "Excavator (Commercial)" +
--         "Excavator (NT)" +
--         "Fork Lift" +
--         "Road Roller" +
--         "Tractor (Commercial)" +
--         "Motorised Cycle (CC  25cc)" +
--         "Bus" +
--         "Semi-Trailer (Commercial)" +
--         "Motor Car" +
--         "Vehicle Fitted With Rig" +
--         "Moped" +
--         "Armoured/Specialised Vehicle" +
--         "Ambulance" +
--         "Animal Ambulance" +
--         "Articulated Vehicle" +
--         "Auxiliary Trailer" +
--         "Camper Van / Trailer" +
--         "Camper Van / Trailer (Private Use)" +
--         "Dumper" +
--         "Educational Institution Bus" +
--         "Fire Fighting Vehicle" +
--         "Fire Tenders" +
--         "Hearses" +
--         "Maxi Cab" +
--         "Mobile Canteen" +
--         "Mobile Clinic" +
--         "Mobile Workshop" +
--         "Omni Bus" +
--         "Private Service Vehicle" +
--         "Private Service Vehicle (Individual Use)" +
--         "Puller Tractor" +
--         "Recovery Vehicle" +
--         "School Bus" +
--         "Snorked Ladders" +
--         "Tow Truck" +
--         "Tower Wagon" +
--         "Tree Trimming Vehicle" +
--         "Vehicle Fitted With Compressor" +
--         "Vehicle Fitted With Generator" +
--         "X-Ray Van" +
--         "Adapted Vehicle" +
--         "M-Cycle/Scooter-With Side Car" +
--         "Motor Cycle/Scooter-Used For Hire" +
--         "Three Wheeler (Personal)" +
--         "Motor Cab" +
--         "Motor Cycle/Scooter-SideCar(T)" +
--         "Quadricycle (Commercial)" +
--         "Quadricycle (Private)" +
--         "Luxury Cab" +
--         "Breakdown Van" +
--         "Cash Van" +
--         "Library Van" +
--         "Omni Bus (Private Use)" +
--         "Vintage Motor Vehicle" +
--         "Trailer For Personal Use" +
--         "Motor Caravan" +
--         "Power Tiller" +
--         "Modular Hydraulic Trailer" +
--         "Bulldozer" +
--         "Motor Cycle/Scooter-With Trailer"
--     );
