-- Generated by tools/build-new-schema.js - do not edit by hand.
--
-- Three tables replacing the ~50 dropped in
-- 20260924130000_drop_all_scope_tables.sql: one table per
-- source (All India, Gujarat RTO-wise, Maharashtra RTO-wise),
-- an rto_code/rto_name row instead of a table per RTO, and
-- month grain from the start rather than year-grain tables
-- with a separate month-grain set behind them.
--
-- 76 vehicle-class columns per table, from
-- tools/class-columns.js - the same array the online import
-- path (supabase/functions/import-workbook) and the offline
-- one (build-month-tables.js) both read, so this schema and
-- whatever writes to it next cannot drift on column names.
--
-- The SELECT-only policy matches every table this project has
-- ever had: the publishable key in script.js stays read-only.
-- Nothing in this migration grants write access to anything -
-- that is a separate RPC, written once real loading starts.

GRANT USAGE ON SCHEMA public TO anon, authenticated;

CREATE TABLE "All_India_Class_Wise" (
    "year" smallint NOT NULL CHECK ("year" BETWEEN 2000 AND 2100)
    , "month" text NOT NULL CHECK ("month" IN ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'))
    , "Maker" text NOT NULL
    , "Three Wheeler (Goods)" integer NOT NULL DEFAULT 0
    , "Three Wheeler (Passenger)" integer NOT NULL DEFAULT 0
    , "e-Rickshaw with Cart (G)" integer NOT NULL DEFAULT 0
    , "e-Rickshaw(P)" integer NOT NULL DEFAULT 0
    , "Tractor-Trolley(Commercial)" integer NOT NULL DEFAULT 0
    , "Trailer (Agricultural)" integer NOT NULL DEFAULT 0
    , "Harvester" integer NOT NULL DEFAULT 0
    , "Goods Carrier" integer NOT NULL DEFAULT 0
    , "M-Cycle/Scooter" integer NOT NULL DEFAULT 0
    , "Trailer (Commercial)" integer NOT NULL DEFAULT 0
    , "Construction Equipment Vehicle" integer NOT NULL DEFAULT 0
    , "Crane Mounted Vehicle" integer NOT NULL DEFAULT 0
    , "Agricultural Tractor" integer NOT NULL DEFAULT 0
    , "Construction Equipment Vehicle (Commercial)" integer NOT NULL DEFAULT 0
    , "Earth Moving Equipment" integer NOT NULL DEFAULT 0
    , "Excavator (Commercial)" integer NOT NULL DEFAULT 0
    , "Excavator (NT)" integer NOT NULL DEFAULT 0
    , "Fork Lift" integer NOT NULL DEFAULT 0
    , "Road Roller" integer NOT NULL DEFAULT 0
    , "Tractor (Commercial)" integer NOT NULL DEFAULT 0
    , "Motorised Cycle (CC  25cc)" integer NOT NULL DEFAULT 0
    , "Bus" integer NOT NULL DEFAULT 0
    , "Semi-Trailer (Commercial)" integer NOT NULL DEFAULT 0
    , "Motor Car" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Rig" integer NOT NULL DEFAULT 0
    , "Moped" integer NOT NULL DEFAULT 0
    , "Armoured/Specialised Vehicle" integer NOT NULL DEFAULT 0
    , "Ambulance" integer NOT NULL DEFAULT 0
    , "Animal Ambulance" integer NOT NULL DEFAULT 0
    , "Articulated Vehicle" integer NOT NULL DEFAULT 0
    , "Auxiliary Trailer" integer NOT NULL DEFAULT 0
    , "Camper Van / Trailer" integer NOT NULL DEFAULT 0
    , "Camper Van / Trailer (Private Use)" integer NOT NULL DEFAULT 0
    , "Dumper" integer NOT NULL DEFAULT 0
    , "Educational Institution Bus" integer NOT NULL DEFAULT 0
    , "Fire Fighting Vehicle" integer NOT NULL DEFAULT 0
    , "Fire Tenders" integer NOT NULL DEFAULT 0
    , "Hearses" integer NOT NULL DEFAULT 0
    , "Maxi Cab" integer NOT NULL DEFAULT 0
    , "Mobile Canteen" integer NOT NULL DEFAULT 0
    , "Mobile Clinic" integer NOT NULL DEFAULT 0
    , "Mobile Workshop" integer NOT NULL DEFAULT 0
    , "Omni Bus" integer NOT NULL DEFAULT 0
    , "Private Service Vehicle" integer NOT NULL DEFAULT 0
    , "Private Service Vehicle (Individual Use)" integer NOT NULL DEFAULT 0
    , "Puller Tractor" integer NOT NULL DEFAULT 0
    , "Recovery Vehicle" integer NOT NULL DEFAULT 0
    , "School Bus" integer NOT NULL DEFAULT 0
    , "Snorked Ladders" integer NOT NULL DEFAULT 0
    , "Tow Truck" integer NOT NULL DEFAULT 0
    , "Tower Wagon" integer NOT NULL DEFAULT 0
    , "Tree Trimming Vehicle" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Compressor" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Generator" integer NOT NULL DEFAULT 0
    , "X-Ray Van" integer NOT NULL DEFAULT 0
    , "Adapted Vehicle" integer NOT NULL DEFAULT 0
    , "M-Cycle/Scooter-With Side Car" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-Used For Hire" integer NOT NULL DEFAULT 0
    , "Three Wheeler (Personal)" integer NOT NULL DEFAULT 0
    , "Motor Cab" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-SideCar(T)" integer NOT NULL DEFAULT 0
    , "Quadricycle (Commercial)" integer NOT NULL DEFAULT 0
    , "Quadricycle (Private)" integer NOT NULL DEFAULT 0
    , "Luxury Cab" integer NOT NULL DEFAULT 0
    , "Breakdown Van" integer NOT NULL DEFAULT 0
    , "Cash Van" integer NOT NULL DEFAULT 0
    , "Library Van" integer NOT NULL DEFAULT 0
    , "Omni Bus (Private Use)" integer NOT NULL DEFAULT 0
    , "Vintage Motor Vehicle" integer NOT NULL DEFAULT 0
    , "Trailer For Personal Use" integer NOT NULL DEFAULT 0
    , "Motor Caravan" integer NOT NULL DEFAULT 0
    , "Power Tiller" integer NOT NULL DEFAULT 0
    , "Modular Hydraulic Trailer" integer NOT NULL DEFAULT 0
    , "Bulldozer" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-With Trailer" integer NOT NULL DEFAULT 0
    , "Power Tiller (Commercial)" integer NOT NULL DEFAULT 0
    , "Total" integer NOT NULL DEFAULT 0
    , "uploaded_at" timestamptz NOT NULL DEFAULT now()
    , PRIMARY KEY ("year", "month", "Maker")
);

ALTER TABLE "All_India_Class_Wise" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "All_India_Class_Wise" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read All_India_Class_Wise" ON "All_India_Class_Wise";

CREATE POLICY "anon read All_India_Class_Wise" ON "All_India_Class_Wise"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Gujarat_RTO_Class_Wise" (
    "year" smallint NOT NULL CHECK ("year" BETWEEN 2000 AND 2100)
    , "month" text NOT NULL CHECK ("month" IN ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'))
    , "rto_code" text NOT NULL
    , "rto_name" text NOT NULL
    , "Maker" text NOT NULL
    , "Three Wheeler (Goods)" integer NOT NULL DEFAULT 0
    , "Three Wheeler (Passenger)" integer NOT NULL DEFAULT 0
    , "e-Rickshaw with Cart (G)" integer NOT NULL DEFAULT 0
    , "e-Rickshaw(P)" integer NOT NULL DEFAULT 0
    , "Tractor-Trolley(Commercial)" integer NOT NULL DEFAULT 0
    , "Trailer (Agricultural)" integer NOT NULL DEFAULT 0
    , "Harvester" integer NOT NULL DEFAULT 0
    , "Goods Carrier" integer NOT NULL DEFAULT 0
    , "M-Cycle/Scooter" integer NOT NULL DEFAULT 0
    , "Trailer (Commercial)" integer NOT NULL DEFAULT 0
    , "Construction Equipment Vehicle" integer NOT NULL DEFAULT 0
    , "Crane Mounted Vehicle" integer NOT NULL DEFAULT 0
    , "Agricultural Tractor" integer NOT NULL DEFAULT 0
    , "Construction Equipment Vehicle (Commercial)" integer NOT NULL DEFAULT 0
    , "Earth Moving Equipment" integer NOT NULL DEFAULT 0
    , "Excavator (Commercial)" integer NOT NULL DEFAULT 0
    , "Excavator (NT)" integer NOT NULL DEFAULT 0
    , "Fork Lift" integer NOT NULL DEFAULT 0
    , "Road Roller" integer NOT NULL DEFAULT 0
    , "Tractor (Commercial)" integer NOT NULL DEFAULT 0
    , "Motorised Cycle (CC  25cc)" integer NOT NULL DEFAULT 0
    , "Bus" integer NOT NULL DEFAULT 0
    , "Semi-Trailer (Commercial)" integer NOT NULL DEFAULT 0
    , "Motor Car" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Rig" integer NOT NULL DEFAULT 0
    , "Moped" integer NOT NULL DEFAULT 0
    , "Armoured/Specialised Vehicle" integer NOT NULL DEFAULT 0
    , "Ambulance" integer NOT NULL DEFAULT 0
    , "Animal Ambulance" integer NOT NULL DEFAULT 0
    , "Articulated Vehicle" integer NOT NULL DEFAULT 0
    , "Auxiliary Trailer" integer NOT NULL DEFAULT 0
    , "Camper Van / Trailer" integer NOT NULL DEFAULT 0
    , "Camper Van / Trailer (Private Use)" integer NOT NULL DEFAULT 0
    , "Dumper" integer NOT NULL DEFAULT 0
    , "Educational Institution Bus" integer NOT NULL DEFAULT 0
    , "Fire Fighting Vehicle" integer NOT NULL DEFAULT 0
    , "Fire Tenders" integer NOT NULL DEFAULT 0
    , "Hearses" integer NOT NULL DEFAULT 0
    , "Maxi Cab" integer NOT NULL DEFAULT 0
    , "Mobile Canteen" integer NOT NULL DEFAULT 0
    , "Mobile Clinic" integer NOT NULL DEFAULT 0
    , "Mobile Workshop" integer NOT NULL DEFAULT 0
    , "Omni Bus" integer NOT NULL DEFAULT 0
    , "Private Service Vehicle" integer NOT NULL DEFAULT 0
    , "Private Service Vehicle (Individual Use)" integer NOT NULL DEFAULT 0
    , "Puller Tractor" integer NOT NULL DEFAULT 0
    , "Recovery Vehicle" integer NOT NULL DEFAULT 0
    , "School Bus" integer NOT NULL DEFAULT 0
    , "Snorked Ladders" integer NOT NULL DEFAULT 0
    , "Tow Truck" integer NOT NULL DEFAULT 0
    , "Tower Wagon" integer NOT NULL DEFAULT 0
    , "Tree Trimming Vehicle" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Compressor" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Generator" integer NOT NULL DEFAULT 0
    , "X-Ray Van" integer NOT NULL DEFAULT 0
    , "Adapted Vehicle" integer NOT NULL DEFAULT 0
    , "M-Cycle/Scooter-With Side Car" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-Used For Hire" integer NOT NULL DEFAULT 0
    , "Three Wheeler (Personal)" integer NOT NULL DEFAULT 0
    , "Motor Cab" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-SideCar(T)" integer NOT NULL DEFAULT 0
    , "Quadricycle (Commercial)" integer NOT NULL DEFAULT 0
    , "Quadricycle (Private)" integer NOT NULL DEFAULT 0
    , "Luxury Cab" integer NOT NULL DEFAULT 0
    , "Breakdown Van" integer NOT NULL DEFAULT 0
    , "Cash Van" integer NOT NULL DEFAULT 0
    , "Library Van" integer NOT NULL DEFAULT 0
    , "Omni Bus (Private Use)" integer NOT NULL DEFAULT 0
    , "Vintage Motor Vehicle" integer NOT NULL DEFAULT 0
    , "Trailer For Personal Use" integer NOT NULL DEFAULT 0
    , "Motor Caravan" integer NOT NULL DEFAULT 0
    , "Power Tiller" integer NOT NULL DEFAULT 0
    , "Modular Hydraulic Trailer" integer NOT NULL DEFAULT 0
    , "Bulldozer" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-With Trailer" integer NOT NULL DEFAULT 0
    , "Power Tiller (Commercial)" integer NOT NULL DEFAULT 0
    , "Total" integer NOT NULL DEFAULT 0
    , "uploaded_at" timestamptz NOT NULL DEFAULT now()
    , PRIMARY KEY ("year", "month", "rto_code", "Maker")
);

ALTER TABLE "Gujarat_RTO_Class_Wise" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Gujarat_RTO_Class_Wise" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Gujarat_RTO_Class_Wise" ON "Gujarat_RTO_Class_Wise";

CREATE POLICY "anon read Gujarat_RTO_Class_Wise" ON "Gujarat_RTO_Class_Wise"
    FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE "Maharashtra_RTO_Class_Wise" (
    "year" smallint NOT NULL CHECK ("year" BETWEEN 2000 AND 2100)
    , "month" text NOT NULL CHECK ("month" IN ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'))
    , "rto_code" text NOT NULL
    , "rto_name" text NOT NULL
    , "Maker" text NOT NULL
    , "Three Wheeler (Goods)" integer NOT NULL DEFAULT 0
    , "Three Wheeler (Passenger)" integer NOT NULL DEFAULT 0
    , "e-Rickshaw with Cart (G)" integer NOT NULL DEFAULT 0
    , "e-Rickshaw(P)" integer NOT NULL DEFAULT 0
    , "Tractor-Trolley(Commercial)" integer NOT NULL DEFAULT 0
    , "Trailer (Agricultural)" integer NOT NULL DEFAULT 0
    , "Harvester" integer NOT NULL DEFAULT 0
    , "Goods Carrier" integer NOT NULL DEFAULT 0
    , "M-Cycle/Scooter" integer NOT NULL DEFAULT 0
    , "Trailer (Commercial)" integer NOT NULL DEFAULT 0
    , "Construction Equipment Vehicle" integer NOT NULL DEFAULT 0
    , "Crane Mounted Vehicle" integer NOT NULL DEFAULT 0
    , "Agricultural Tractor" integer NOT NULL DEFAULT 0
    , "Construction Equipment Vehicle (Commercial)" integer NOT NULL DEFAULT 0
    , "Earth Moving Equipment" integer NOT NULL DEFAULT 0
    , "Excavator (Commercial)" integer NOT NULL DEFAULT 0
    , "Excavator (NT)" integer NOT NULL DEFAULT 0
    , "Fork Lift" integer NOT NULL DEFAULT 0
    , "Road Roller" integer NOT NULL DEFAULT 0
    , "Tractor (Commercial)" integer NOT NULL DEFAULT 0
    , "Motorised Cycle (CC  25cc)" integer NOT NULL DEFAULT 0
    , "Bus" integer NOT NULL DEFAULT 0
    , "Semi-Trailer (Commercial)" integer NOT NULL DEFAULT 0
    , "Motor Car" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Rig" integer NOT NULL DEFAULT 0
    , "Moped" integer NOT NULL DEFAULT 0
    , "Armoured/Specialised Vehicle" integer NOT NULL DEFAULT 0
    , "Ambulance" integer NOT NULL DEFAULT 0
    , "Animal Ambulance" integer NOT NULL DEFAULT 0
    , "Articulated Vehicle" integer NOT NULL DEFAULT 0
    , "Auxiliary Trailer" integer NOT NULL DEFAULT 0
    , "Camper Van / Trailer" integer NOT NULL DEFAULT 0
    , "Camper Van / Trailer (Private Use)" integer NOT NULL DEFAULT 0
    , "Dumper" integer NOT NULL DEFAULT 0
    , "Educational Institution Bus" integer NOT NULL DEFAULT 0
    , "Fire Fighting Vehicle" integer NOT NULL DEFAULT 0
    , "Fire Tenders" integer NOT NULL DEFAULT 0
    , "Hearses" integer NOT NULL DEFAULT 0
    , "Maxi Cab" integer NOT NULL DEFAULT 0
    , "Mobile Canteen" integer NOT NULL DEFAULT 0
    , "Mobile Clinic" integer NOT NULL DEFAULT 0
    , "Mobile Workshop" integer NOT NULL DEFAULT 0
    , "Omni Bus" integer NOT NULL DEFAULT 0
    , "Private Service Vehicle" integer NOT NULL DEFAULT 0
    , "Private Service Vehicle (Individual Use)" integer NOT NULL DEFAULT 0
    , "Puller Tractor" integer NOT NULL DEFAULT 0
    , "Recovery Vehicle" integer NOT NULL DEFAULT 0
    , "School Bus" integer NOT NULL DEFAULT 0
    , "Snorked Ladders" integer NOT NULL DEFAULT 0
    , "Tow Truck" integer NOT NULL DEFAULT 0
    , "Tower Wagon" integer NOT NULL DEFAULT 0
    , "Tree Trimming Vehicle" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Compressor" integer NOT NULL DEFAULT 0
    , "Vehicle Fitted With Generator" integer NOT NULL DEFAULT 0
    , "X-Ray Van" integer NOT NULL DEFAULT 0
    , "Adapted Vehicle" integer NOT NULL DEFAULT 0
    , "M-Cycle/Scooter-With Side Car" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-Used For Hire" integer NOT NULL DEFAULT 0
    , "Three Wheeler (Personal)" integer NOT NULL DEFAULT 0
    , "Motor Cab" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-SideCar(T)" integer NOT NULL DEFAULT 0
    , "Quadricycle (Commercial)" integer NOT NULL DEFAULT 0
    , "Quadricycle (Private)" integer NOT NULL DEFAULT 0
    , "Luxury Cab" integer NOT NULL DEFAULT 0
    , "Breakdown Van" integer NOT NULL DEFAULT 0
    , "Cash Van" integer NOT NULL DEFAULT 0
    , "Library Van" integer NOT NULL DEFAULT 0
    , "Omni Bus (Private Use)" integer NOT NULL DEFAULT 0
    , "Vintage Motor Vehicle" integer NOT NULL DEFAULT 0
    , "Trailer For Personal Use" integer NOT NULL DEFAULT 0
    , "Motor Caravan" integer NOT NULL DEFAULT 0
    , "Power Tiller" integer NOT NULL DEFAULT 0
    , "Modular Hydraulic Trailer" integer NOT NULL DEFAULT 0
    , "Bulldozer" integer NOT NULL DEFAULT 0
    , "Motor Cycle/Scooter-With Trailer" integer NOT NULL DEFAULT 0
    , "Power Tiller (Commercial)" integer NOT NULL DEFAULT 0
    , "Total" integer NOT NULL DEFAULT 0
    , "uploaded_at" timestamptz NOT NULL DEFAULT now()
    , PRIMARY KEY ("year", "month", "rto_code", "Maker")
);

ALTER TABLE "Maharashtra_RTO_Class_Wise" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "Maharashtra_RTO_Class_Wise" TO anon, authenticated;

DROP POLICY IF EXISTS "anon read Maharashtra_RTO_Class_Wise" ON "Maharashtra_RTO_Class_Wise";

CREATE POLICY "anon read Maharashtra_RTO_Class_Wise" ON "Maharashtra_RTO_Class_Wise"
    FOR SELECT TO anon, authenticated USING (true);

NOTIFY pgrst, 'reload schema';
